#
# token for login
#
# extract with
#
# kubectl get secret training -o jsonpath='{.data.token}' | base64 --decode
#
apiVersion: v1
data:
  token: ODFlNGEyNmQ3NWU4YTg1ZDk4YmMzYTFjZTFlOWQzNDkyODBkMGUxYTg5ZmI0NjUx
kind: Secret
metadata:
  name: training
  namespace: default
type: Opaque
