name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/thomasfricke/minikube:latest
        docker tag minikube:latest ghcr.io/thomasfricke/minikube:v0.0.27
    
    - name: Push to registry
      run: |
        docker push ghcr.io/thomasfricke/minikube:v0.0.27
        docker push ghcr.io/thomasfricke/minikube:latest
        
